export const DTC_PROTOCOL_VERSION = 8;

export const DTC_MESSAGE_TYPES = {
  LOGON_REQUEST: 1,
  LOGON_RESPONSE: 2,
  HEARTBEAT: 3,
  LOGOFF: 5,
  ENCODING_REQUEST: 6,
  ENCODING_RESPONSE: 7,
  MARKET_DATA_FEED_STATUS: 100,
  MARKET_DATA_REQUEST: 101,
  MARKET_DEPTH_REQUEST: 102,
  MARKET_DATA_REJECT: 103,
  MARKET_DATA_SNAPSHOT: 104,
  MARKET_DEPTH_UPDATE_LEVEL: 106,
  MARKET_DATA_UPDATE_TRADE: 107,
  MARKET_DATA_UPDATE_BID_ASK: 108,
  MARKET_DATA_UPDATE_TRADE_COMPACT: 112,
  MARKET_DATA_UPDATE_SESSION_VOLUME: 113,
  MARKET_DATA_UPDATE_SESSION_HIGH: 114,
  MARKET_DATA_UPDATE_SESSION_LOW: 115,
  MARKET_DATA_FEED_SYMBOL_STATUS: 116,
  MARKET_DATA_UPDATE_BID_ASK_COMPACT: 117,
  MARKET_DATA_UPDATE_SESSION_SETTLEMENT: 119,
  MARKET_DATA_UPDATE_SESSION_OPEN: 120,
  MARKET_DEPTH_REJECT: 121,
  MARKET_DEPTH_SNAPSHOT_LEVEL: 122,
  MARKET_DATA_UPDATE_LAST_TRADE_SNAPSHOT: 134,
  MARKET_DATA_UPDATE_OPEN_INTEREST: 135,
  MARKET_DATA_UPDATE_TRADE_WITH_UNBUNDLED_INDICATOR: 137,
  MARKET_DATA_UPDATE_TRADE_NO_TIMESTAMP: 142,
  MARKET_DATA_UPDATE_BID_ASK_NO_TIMESTAMP: 143,
  MARKET_DATA_UPDATE_BID_ASK_FLOAT_WITH_MICROSECONDS: 144,
  MARKET_DEPTH_SNAPSHOT_LEVEL_FLOAT: 145,
  MARKET_DATA_UPDATE_TRADE_WITH_UNBUNDLED_INDICATOR_2: 146,
  MARKET_DATA_UPDATE_TRADE_V2: 147,
  MARKET_DATA_UPDATE_BID_ASK_DOUBLE_WITH_MICROSECONDS: 148,
} as const;

export const DTC_ENCODING = {
  BINARY: 0,
} as const;

export const DTC_LOGON_STATUS = {
  SUCCESS: 1,
  ERROR: 2,
  ERROR_NO_RECONNECT: 3,
  RECONNECT_NEW_ADDRESS: 4,
} as const;

export const DTC_REQUEST_ACTION = {
  SUBSCRIBE: 1,
  UNSUBSCRIBE: 2,
} as const;

export const DTC_BID_ASK = {
  UNSET: 0,
  AT_BID: 1,
  AT_ASK: 2,
} as const;

export const DTC_MARKET_DEPTH_UPDATE_TYPE = {
  UNSET: 0,
  INSERT_UPDATE_LEVEL: 1,
  DELETE_LEVEL: 2,
} as const;

export const DTC_FINAL_UPDATE_IN_BATCH = {
  UNSET: 0,
  TRUE: 1,
  FALSE: 2,
  BEGIN_BATCH: 3,
} as const;

export const DTC_STRUCT_SIZES = {
  MESSAGE_HEADER: 4,
  ENCODING_REQUEST: 16,
  LOGON_REQUEST: 284,
  HEARTBEAT: 16,
  MARKET_DATA_REQUEST: 96,
  MARKET_DEPTH_REQUEST: 96,
} as const;
